import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ReactQueryProviderWrapper from "@/context/QueryProvider";
import { ToastProvider } from "@/context/ToastProvider";
import { AthleteCardVisibilityProvider } from "@/context/AthleteCardVisibilityProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProviderWrapper>
      <ClerkProvider>
        <AthleteCardVisibilityProvider>
          <html lang="en">
            <body className={inter.className}>
              <ToastProvider> {children} </ToastProvider>
            </body>
          </html>
        </AthleteCardVisibilityProvider>
      </ClerkProvider>
    </ReactQueryProviderWrapper>
  );
}
