name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.12.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      NEXT_PUBLIC_WEBSITE_URL: ${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}
      NEXT_PUBLIC_SUPPORT_EMAIL: ${{ secrets.NEXT_PUBLIC_SUPPORT_EMAIL }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      NEXT_PUBLIC_ATHLETE_TIER_1_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_ATHLETE_TIER_1_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_ATHLETE_TIER_2_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_ATHLETE_TIER_2_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_ATHLETE_TIER_3_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_ATHLETE_TIER_3_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_ATHLETE_TIER_1_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_ATHLETE_TIER_1_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_ATHLETE_TIER_2_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_ATHLETE_TIER_2_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_ATHLETE_TIER_3_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_ATHLETE_TIER_3_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_TEAM_TIER_1_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_TEAM_TIER_1_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_TEAM_TIER_2_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_TEAM_TIER_2_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_TEAM_TIER_3_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_TEAM_TIER_3_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_TEAM_TIER_1_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_TEAM_TIER_1_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_TEAM_TIER_2_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_TEAM_TIER_2_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_TEAM_TIER_3_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_TEAM_TIER_3_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_BRAND_BASIC_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_BRAND_BASIC_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_BRAND_PERFORMANCE_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_BRAND_PERFORMANCE_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_BRAND_ADVANCED_MONTHLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_BRAND_ADVANCED_MONTHLY_PRICE_ID }}
      NEXT_PUBLIC_BRAND_BASIC_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_BRAND_BASIC_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_BRAND_PERFORMANCE_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_BRAND_PERFORMANCE_YEARLY_PRICE_ID }}
      NEXT_PUBLIC_BRAND_ADVANCED_YEARLY_PRICE_ID: ${{ secrets.NEXT_PUBLIC_BRAND_ADVANCED_YEARLY_PRICE_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Change Directory
        run: cd /home/aryan/actions-runner/_work/app/app
      - run: pm2 restart 0
